export const pretest = [
    {
        id: 1,
        soal: 'Efek rumah kaca adalah salah satu penyebab utama pemanasan global. Masalah ini terjadi akibat gas-gas tertentu yang memerangkap panas di atmosfer. Faktor yang memperburuk efek rumah kaca adalah…',
        pilihan: ['Meningkatnya kadar gas metana di atmosfer', 'Penurunan kadar karbon dioksida di atmosfer', 'Radiasi sinar ultraviolet masuk ke bumi', 'Meningkatnya kadar oksigen di atmosfer'],
        kunci: 0,
        gambar: null,
    },
    {
        id: 2,
        soal: 'Pemanasan global berdampak pada berbagai sektor kehidupan,tidak terkecuali pada bidang ekologi. Salah satu contoh dampak pemanasan global di bidang ekologi adalah…',
        pilihan: ['Perubahan habitat beruang laut', 'Penipisan lapisan ozon', 'Mencairnya es dan gletser', 'Perubahan pola cuaca'],
        kunci: 0,
        gambar: null,
    },
    {
        id: 3,
        soal: 'Aktivitas berikut yang tidak dapat menghasilkan gas rumah kaca adalah...',
        pilihan: ['Pertanian dan peternakan', 'Asap kendaraan bermotor', 'Penggunaan pendingin ruangan', 'Kelautan dan perikanan'],
        kunci: 3,
        gambar: null,
    },
    {
        id: 4,
        soal: 'Perubahan iklim akibat pemanasan global memengaruhi sektor pertanian di seluruh dunia. Dampak utama yang dialami sektor pertanian akibat pemanasan global adalah…',
        pilihan: ['Pola tanam menjadi lebih stabil karena suhu yang lebih hangat sepanjang tahun', 'Risiko gagal panen meningkat karena perubahan pola hujan dan serangan hama', 'Meningkatnya ketersediaan air untuk irigasi di wilayah kering', 'Produksi pangan meningkat karena musim tanam yang lebih panjang'],
        kunci: 1,
        gambar: null,
    },
    {
        id: 5,
        soal: 'Berikut ini yang tidak dipengaruhi oleh pemanasan global terhadap ekosistem adalah…',
        pilihan: ['Hilangnya wilayah tempat tinggal makhluk hidup', 'Peningkatan spesies yang dapat beradaptasi', 'Ketidakstabilan rantai makanan', 'Terganggunya pola reproduksi spesies tertentu'],
        kunci: 1,
        gambar: null,
    },
    {
        id: 6,
        soal: 'Yang termasuk dampak dari pemanasan global ditunjukkan oleh nomor',
        pilihan: ['1, 2, dan 4', '2, 3, dan 5', '3, 4, dan 5', '1, 3, dan 5'],
        kunci: 0,
        gambar: require('../assets/question/pretest_6.png'),
    },
    {
        id: 7,
        soal: 'Bagaimana hubungan ketiga peristiwa diatas dengan pemanasan global?',
        pilihan: ['Mencairnya es di kutup berkontribusi pada kenaikan permukaan laut, yang menyebabkan banjir di kawasan pesisir. Hal ini juga memengaruhi pola curah hujan dan dapat menyebabkan kekeringan di wilayah yang sebelumnya subur.',
            'Pemanasan global mempercepat proses mencairnya es di kutub, yang mengganggu keseimbangan ekosistem dan dapat menciptakan kondisi cuaca ekstrem, termasuk kekeringan dan banjir, di berbagai belahan dunia.',
            'Mencairnya es di kutub dan fenomena cuaca ekstrem, seperti kekeringan dan banjir, menunjukkan bahwa perubahan iklim adalah siklus alami, sehingga hubungan ini tidak langsung mempengaruhi satu sama lain.',
            'Dampak dari pemanasan global pada mencairnya es dan pola cuaca menunjukkan bahwa pengelolaan sumber daya air yang lebih baik diperlukan untuk mengatasi potensi banjir dan kekeringan di masa depan, yang berkaitan dengan perubahan iklim.'
        ],
        kunci: 1,
        gambar: require('../assets/question/pretest_7.png'),
    },
    {
        id: 8,
        soal: 'Tindakan yang paling efektif untuk mengurangi emisi gas rumah kaca adalah',
        pilihan: ['1, 2, dan 5', '1, 3, dan 4', '2, 4, dan 5', '3, 4, dan 5'],
        kunci: 0,
        gambar: require('../assets/question/pretest_8.png'),
    },
    {
        id: 9,
        soal: 'Berdasarkan peristiwa tersebut, bagaimana proses pemanasan global dapat menyebabkan kejadian banjir seperti yang terlihat pada gambar?',
        pilihan: ['Pemanasan global membuat permukaan bumi menjadi lebih panas sehingga semua air di daratan langsung menguap dan menyebabkan hujan lebat yang berlebihan.',
            'Pemanasan global menyebabkan mencairnya es di kutub, yang kemudian meningkatkan jumlah air laut dan mengakibatkan naiknya permukaan laut sehingga menyebabkan banjir di daerah daratan rendah.',
            'Pemanasan global mempercepat proses penguapan air dari lautan, meningkatkan curah hujan yang berlebihan, dan menyebabkan perubahan pola musim hujan sehingga banjir menjadi lebih sering terjadi.',
            'Pemanasan global membuat tanah menjadi lebih subur, sehingga ketika hujan turun, banjir bisa dihindari karena tanah lebih mampu menyerap air dengan cepat.'],
        kunci: 2,
        gambar: require('../assets/question/pretest_9.png'),
    },
    {
        id: 10,
        soal: 'Komponen pada penggunaan alat transportasi yang menyebabkan terjadinya peningkatan suhu udara adalah',
        pilihan: ['Pembakaran yang terjadi didalam mesin tidak sempurna',
            "Emisi CO2 dari bahan bakar transportasi",
            'Banyaknya penggunaan transportasi',
            'Energi yang dihasilkan dari proses pemanasan'
        ],
        kunci: 1,
        gambar: null,
    },
    {
        id: 11,
        soal: 'Dari pernyataan di atas, yang tidak termasuk ke dalam dampak dari fenomena pemanasan global adalah',
        pilihan: ['Suhu bumi semakin meningkat.',
            'Mencairnya es di kutub sehingga menyebabkan permukaan air laut meningkat.',
            'Kenaikan populasi spesies hewan dan tumbuhan.',
            'Lapisan ozon semakin menipis.'
        ],
        kunci: 2,
        gambar: require('../assets/question/pretest_11.png'),
    },
    {
        id: 12,
        soal: 'Sebagai siswa yang ingin berkontribusi terhadap lingkungan, langkah apa yang paling efektif dan dapat dilakukan bersama-sama oleh siswa untuk membantu mengurangi polusi udara, sambil mempertimbangkan aktivitas sekolah dan kebutuhan masyarakat sehari-hari?',
        pilihan: ['Menyampaikan petisi kepada pemerintah untuk melarang seluruh kendaraan bermotor di kota, meskipun tidak ada alternatif transportasi lain yang tersedia.',
            'Mengurangi kegiatan belajar di luar ruangan ketika polusi udara tinggi, tanpa melakukan tindakan lain untuk mengurangi sumber polusi.',
            'Membuat gerakan sekolah untuk menanam pohon di sekitar lingkungan sekolah dan mengajak teman untuk bersepeda atau berjalan kaki ke sekolah.',
            'Menggalang dana di sekolah untuk membeli lebih banyak kendaraan bermotor pribadi agar perjalanan lebih cepat, walaupun akan meningkatkan polusi udara.'
        ],
        kunci: 2,
        gambar: require('../assets/question/pretest_12.png'),
    },
    {
        id: 13,
        soal: 'Efek rumah kaca dapat berdampak pada pemanasan global. Salah satu usaha yang dapat dilakukan untuk mengurangi terjadinya efek rumah kaca adalah',
        pilihan: ['Membatasi penggunaan kompos',
            'Meningkatkan pembangunan pabrik',
            'Membatasi pemakaian bahan bakar fosil',
            'Meningkatkan produksi sepeda motor'
        ],
        kunci: 2,
        gambar: null,
    },
    {
        id: 14,
        soal: 'Berdasarkan pada data diatas, simpulkan data tersebut terkait keterkaitan suhu rata-rata bulanan Indonesia pada tahun 1991-2020 dan suhu rata-rata bulanan Indonesia pada tahun 2022!',
        pilihan: ['Suhu rata-rata bulanan Indonesia pada tahun 2022 selalu lebih rendah dibandingkan suhu normal rata-rata bulanan 1991–2020.',
            'Suhu rata-rata bulanan Indonesia pada tahun 2022 menunjukkan pola yang lebih tinggi dari suhu normal rata-rata bulanan 1991–2020 di beberapa bulan tertentu.',
            'Tidak ada perubahan signifikan antara suhu rata-rata bulanan 2022 dan suhu normal rata-rata bulanan 1991–2020.',
            'Suhu rata-rata bulanan 2022 selalu konsisten sama dengan suhu normal rata-rata bulanan 1991–2020 sepanjang tahun.'
        ],
        kunci: 1,
        gambar: require('../assets/question/pretest_14.png'),
    },
    {
        id: 15,
        soal: 'Gas-gas di atmosfer yang dapat menangkap panas matahari disebut gas rumah kaca. Yang termasuk gas rumah kaca yang ada di atmosfer antara lain adalah karbon dioksida (CO2), nitrogen dioksida (N2O), metana (CH4), gas F, freon (SF6, HFC dan PFC),dll. Berdasarkan tabel diatas, tentukan sektor mana yang termasuk dalam golongan penyumbang gas rumah kaca ke atmosfer paling banyak?',
        pilihan: ['Sektor Pertanian', 'Sektor Industri', 'Sektor Energi lain', 'Sektor Bangunan'],
        kunci: 1,
        gambar: require('../assets/question/pretest_15.png'),
    },
    {
        id: 16,
        soal: 'Meningkatnya jumlah kendaraan bermotor mengakibatkan naiknya suhu udara di daerah perkotaan yang dapat mengganggu proses pernafasan makhluk hidup.Gas buangan dari kendaraan tersebut bersifat sebagai gas rumah kaca dan racun bagi tubuh. Salah satu altrenatif untuk mengatasi masalah tersebut yang paling tepat adalah',
        pilihan: ['Membuat saringan CO2 ditempat-tempat tertentu',
            'Membuat alat deteksi CO2 pada kendaraan bermotor',
            'Memberi penyuluhan tentang kesehatan lingkungan',
            'Menggalakkan kegiatan penghijauan di kota besar'
        ],
        kunci: 3,
        gambar: null,
    },
    {
        id: 17,
        soal: 'Pemanasan global menyebabkan mencairnya es di kutub, yang berkontribusi pada kenaikan permukaan laut. Apa dampak yang mungkin terjadi jika hal ini terus terjadi pada wilayah pesisir?',
        pilihan: ['Kenaikan permukaan laut akan memperluas wilayah daratan di pesisir sehingga menguntungkan masyarakat setempat.',
            'Banjir rob dan abrasi akan semakin sering terjadi, yang mengancam pemukiman dan aktivitas ekonomi di wilayah pesisir.',
            'Kehidupan di wilayah pesisir tidak akan terpengaruh karena air laut akan segera surut dengan sendirinya.',
            'Kenaikan permukaan laut akan menciptakan habitat baru untuk ikan, sehingga meningkatkan hasil tangkapan nelayan.'
        ],
        kunci: 1,
        gambar: null,
    },
    {
        id: 18,
        soal: 'Berdasarkan pola yang terlihat pada kedua gambar tersebut, mengapa terumbu karang pada gambar kedua mengalami pemutihan jika dikaitkan dengan fenomena pemanasan global?',
        pilihan: ['Pemutihan terjadi karena peningkatan suhu air laut akibat pemanasan global, yang menyebabkan stres pada karang dan kehilangan alga simbiotik.',
            'Pemutihan terjadi karena penurunan kadar oksigen di air laut akibat aktivitas fotosintesis alga yang berlebihan.',
            'Pemutihan terjadi karena pencemaran laut oleh limbah plastik yang mempercepat kerusakan ekosistem karang.',
            'Pemutihan terjadi karena perubahan salinitas air laut akibat meningkatnya volume es yang mencair. '
        ],
        kunci: 0,
        gambar: require('../assets/question/pretest_18.png'),
    },
    {
        id: 19,
        soal: 'Beberapa hal yang dapat mengurangi tingkat pemanasan global di lingkungan sekolah antara lain menggunakan transportasi umum, meminimalisir penggunaan pendingin ruangan, dan melakukan penanaman pohon. Mengapa langkah-langkah tersebut dapat mengurangi pemanasan global?',
        pilihan: ['Karena dapat mengurangi jumlah sampah di lingkungan sekolah.',
            'Karena dapat mengurangi emisi gas rumah kaca dan meningkatkan kualitas udara.',
            'Karena dapat menghemat uang sekolah.',
            'Karena dapat meningkatkan kenyamanan di sekolah.'
        ],
        kunci: 1,
        gambar: null,
    },
    {
        id: 20,
        soal: 'Benda yang tidak menggunakan bahan CFC ada pada nomor',
        pilihan: ['Lemari Es', 'Pendingin Ruangan', 'Oven Listrik', 'Deodoran Semprot'],
        kunci: 2,
        gambar: require('../assets/question/pretest_20.png'),
    },
]