export const pretest = [
    {
        id: 1,
        soal: 'Efek rumah kaca adalah salah satu penyebab utama pemanasan global. Masalah ini terjadi akibat gas-gas tertentu yang memerangkap panas di atmosfer. Faktor yang memperburuk efek rumah kaca adalah…',
        pilihan: ['Meningkatnya kadar gas metana di atmosfer', 'Penurunan kadar karbon dioksida di atmosfer', 'Radiasi sinar ultraviolet masuk ke bumi', 'Meningkatnya kadar oksigen di atmosfer'],
        kunci: 0,
        gambar: null,
    },
    {
        id: 2,
        soal: 'Pemanasan global berdampak pada berbagai sektor kehidupan,tidak terkecuali pada bidang ekologi. Salah satu contoh dampak pemanasan global di bidang ekologi adalah…',
        pilihan: ['Perubahan habitat beruang laut', 'Penipisan lapisan ozon', 'Mencairnya es dan gletser', 'Perubahan pola cuaca'],
        kunci: 0,
        gambar: null,
    },
    {
        id: 3,
        soal: 'Aktivitas berikut yang tidak dapat menghasilkan gas rumah kaca adalah...',
        pilihan: ['Pertanian dan peternakan', 'Asap kendaraan bermotor', 'Penggunaan pendingin ruangan', 'Kelautan dan perikanan'],
        kunci: 3,
        gambar: null,
    },
    {
        id: 4,
        soal: 'Perubahan iklim akibat pemanasan global memengaruhi sektor pertanian di seluruh dunia. Dampak utama yang dialami sektor pertanian akibat pemanasan global adalah…',
        pilihan: ['Pola tanam menjadi lebih stabil karena suhu yang lebih hangat sepanjang tahun', 'Risiko gagal panen meningkat karena perubahan pola hujan dan serangan hama', 'Meningkatnya ketersediaan air untuk irigasi di wilayah kering', 'Produksi pangan meningkat karena musim tanam yang lebih panjang'],
        kunci: 1,
        gambar: null,
    },
    {
        id: 5,
        soal: 'Berikut ini yang tidak dipengaruhi oleh pemanasan global terhadap ekosistem adalah…',
        pilihan: ['Hilangnya wilayah tempat tinggal makhluk hidup', 'Peningkatan spesies yang dapat beradaptasi', 'Ketidakstabilan rantai makanan', 'Terganggunya pola reproduksi spesies tertentu'],
        kunci: 1,
        gambar: null,
    },
    {
        id: 6,
        soal: 'Yang termasuk dampak dari pemanasan global ditunjukkan oleh nomor',
        pilihan: ['1, 2, dan 4', '2, 3, dan 5', '3, 4, dan 5', '1, 3, dan 5'],
        kunci: 0,
        gambar: require('../assets/question/pretest_6.png'),
    },
    {
        id: 7,
        soal: 'Bagaimana hubungan ketiga peristiwa diatas dengan pemanasan global?',
        pilihan: ['Mencairnya es di kutup berkontribusi pada kenaikan permukaan laut, yang menyebabkan banjir di kawasan pesisir. Hal ini juga memengaruhi pola curah hujan dan dapat menyebabkan kekeringan di wilayah yang sebelumnya subur.',
            'Pemanasan global mempercepat proses mencairnya es di kutub, yang mengganggu keseimbangan ekosistem dan dapat menciptakan kondisi cuaca ekstrem, termasuk kekeringan dan banjir, di berbagai belahan dunia.',
            'Mencairnya es di kutub dan fenomena cuaca ekstrem, seperti kekeringan dan banjir, menunjukkan bahwa perubahan iklim adalah siklus alami, sehingga hubungan ini tidak langsung mempengaruhi satu sama lain.',
            'Dampak dari pemanasan global pada mencairnya es dan pola cuaca menunjukkan bahwa pengelolaan sumber daya air yang lebih baik diperlukan untuk mengatasi potensi banjir dan kekeringan di masa depan, yang berkaitan dengan perubahan iklim.'
        ],
        kunci: 1,
        gambar: require('../assets/question/pretest_7.png'),
    },
    {
        id: 8,
        soal: 'Tindakan yang paling efektif untuk mengurangi emisi gas rumah kaca adalah',
        pilihan: ['1, 2, dan 5', '1, 3, dan 4', '2, 4, dan 5', '3, 4, dan 5'],
        kunci: 0,
        gambar: require('../assets/question/pretest_8.png'),
    },
    {
        id: 9,
        soal: 'Berdasarkan peristiwa tersebut, bagaimana proses pemanasan global dapat menyebabkan kejadian banjir seperti yang terlihat pada gambar?',
        pilihan: ['Pemanasan global membuat permukaan bumi menjadi lebih panas sehingga semua air di daratan langsung menguap dan menyebabkan hujan lebat yang berlebihan.',
            'Pemanasan global menyebabkan mencairnya es di kutub, yang kemudian meningkatkan jumlah air laut dan mengakibatkan naiknya permukaan laut sehingga menyebabkan banjir di daerah daratan rendah.',
            'Pemanasan global mempercepat proses penguapan air dari lautan, meningkatkan curah hujan yang berlebihan, dan menyebabkan perubahan pola musim hujan sehingga banjir menjadi lebih sering terjadi.',
            'Pemanasan global membuat tanah menjadi lebih subur, sehingga ketika hujan turun, banjir bisa dihindari karena tanah lebih mampu menyerap air dengan cepat.'],
        kunci: 2,
        gambar: require('../assets/question/pretest_9.png'),
    },
    {
        id: 10,
        soal: 'Komponen pada penggunaan alat transportasi yang menyebabkan terjadinya peningkatan suhu udara adalah',
        pilihan: ['Pembakaran yang terjadi didalam mesin tidak sempurna',
            "Emisi CO2 dari bahan bakar transportasi",
            'Banyaknya penggunaan transportasi',
            'Energi yang dihasilkan dari proses pemanasan'
        ],
        kunci: 1,
        gambar: null,
    },
]